### PR TITLE
add query isHibernated

### PR DESCRIPTION
**Pull request by nenohi**
一旦これでなんとかならんですか
## Checklist
- [ ] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [ ] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [ ] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

### CODE REVIEW

**Comment by u1-liquid** [comment]
ならないですね

**Comment by nenohi** [comment]
__chart__per_user_followingから取ってくるとか良さそう？

**Comment by nenohi** [comment]
followingだから逆か

**Comment by nenohi** [comment]
PerUserPvChartを使う方向で

**Pull request closed without merging**
